{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ui-service
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.hpa.maxreplicas }}
  minReplicas: {{ .Values.hpa.minrplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-ui-dep
  targetCPUUtilizationPercentage: {{ .Values.hpa.cuputi }}
  {{- end -}}